name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      run: docker login --username geniuslat --password ${{ secrets.PAT }} ghcr.io

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/geniuslat/automatic-image:latest

    - name: Push the Docker image
      run: docker push ghcr.io/geniuslat/automatic-image:latest

