name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install black
        run: pip install black
      
      - name: Format code
        run: black . --check || (black . && git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com' && git add . && git commit -m 'Format code with black' && git push)

      - name: Install flake8
        run: pip install flake8

      - name: Lint with flake8
        run: flake8 .
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      run: docker login --username geniuslat --password ${{ secrets.PAT }} ghcr.io

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/geniuslat/automatic-image:latest

    - name: Push the Docker image
      run: docker push ghcr.io/geniuslat/automatic-image:latest
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используйте встроенный токен
        run: |
          twine upload --repository-url https://upload.github.com/geniuslat/MlOps3Hw1/packages/ -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" .



